# Generated by Django 4.1.3 on 2022-12-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M14', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
